repos:
  - repo: https://github.com/LiquidFun/aoc_tiles
    rev: 0.7.2
    hooks:
      - id: aoc-tiles
        args:
          - --auto-add-tiles-to-git=amend
          - --what-to-show-on-right-side=checkmark
          - --language-sorting=scala,go,py,ipynb
          - --count-as-solved-when=on_leaderboard
